# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: TestAgentPool

steps:
- script: echo Hello, whhjorld!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell comhjbdsjdsbmands here.
      
      Write-Host "Hello World"
      Write-Host 'Hi'
      $v= $env:SYSTEM_ACCESSTOKEN

      $msiResponse = Invoke-WebRequest -Uri "http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https://management.azure.com/" `
              -Headers @{Metadata = "true" } -UseBasicParsing
      $msiContent = $msiResponse.Content | ConvertFrom-Json
      $access_token = $msiContent.access_token
      Write-Host $access_token
  env:
    system_accesstoken: $(System.AccessToken)
